"""Guide sheet content (one tuple per row; column A carries the text).

Kept verbatim from the legacy template so the in-workbook manual stays
the single onboarding document. Update alongside feature changes.
"""

_WHATS_NEW: list[tuple[str, ...]] = [
    (),
    ("WHAT'S NEW IN THIS VERSION",),
    ('  - One updater for everything: run "Update Portfolio" (no more three .bat files).',),
    ('    It backs up your file first (backups folder), works on Windows and Mac.',),
    ('  - PPF, done properly: list your deposits on the PPF_Ledger sheet and Balance,',),
    ('    interest and XIRR are computed by the official monthly-minimum-balance rule',),
    ('    with the real historical rates. No ledger? Your typed balance is used as before.',),
    ('  - Net worth over time: each run records a dated snapshot on the History sheet;',),
    ('    the Dashboard shows a trend line. Just keep running the updater.',),
    ('  - Adding a family member is now a question: the updater asks "Add a new person?"',),
    ('    and builds their sheet from your answer - no need to know where to type.',),
    ('  - Green = gain, red = loss, everywhere. Amber = look closer: a stale price,',),
    ('    a suspended/delisted stock, or an estimated cost.',),
    ('  - Splits & bonuses handled automatically, checked on BOTH NSE and BSE: the',),
    ('    Corporate_Actions sheet lists what was fetched for your stocks, and the',),
    ("    Equity 'Qty today' / 'Avg cost today' columns show your holding exactly as",),
    ('    your demat does (e.g. 100 shares become 200 after a 1:1 bonus) - all with',),
    ('    zero action from you. Your typed Quantity/Avg cost always stay as bought.',),
    ('    If a stock cannot be verified on either exchange, the updater SAYS SO by',),
    ('    name in its summary - nothing is skipped silently.',),
    ("  - Old purchase, price unknown? Leave Avg. cost BLANK if bought before Feb-2018 -",),
    ('    the 31-Jan-2018 FMV (tax grandfathering value) fills in, marked amber.',),
    ('  - FDs: pick the bank from the dropdown. Bonds: maturity value + coupons counted.',),
    ("  - Dashboard: 'Expected @ FY-end' estimates each person's total at 31 March,",),
    ("    using your 'Expected return %' input for market assets.",),
]

GUIDE_ROWS: list[tuple[str, ...]] = [
    ('HOW TO USE THIS TRACKER',),
    (),
    (),
    ("This one workbook tracks the whole family's net worth across asset classes.",),
    ('The Dashboard adds everything up automatically with formulas — you never edit formulas.',),
    (),
    ('ADD A NEW PERSON',),
    ('  - Easiest: when you run "Update Portfolio", it asks "Add a new person?" -',),
    ('    type a name and their sheet, Dashboard row and columns are created for you.',),
    ('  - Or do it by hand: type the name into an empty yellow "Person" cell on the',),
    ('    Dashboard (rows 6-15); the next update builds their sheet.',),
    ('  - Then record their holdings using that same name in the Owner columns.',),
    ("    Their totals roll into the family total and charts automatically.",),
    (),
    ('ADD A HOLDING',),
    ('  - Equity: add a row on Equity - Owner, then PICK the Scrip from the dropdown',),
    ("    (ISIN fills in from Stock_Master), Qty, Avg cost. 'Cost date' drives the per-stock",),
    ('    XIRR - pre-set to 31-Jan-2018 (FMV grandfathering) or the IPO date for post-2018',),
    ('    listings; replace with your actual purchase date for precision.',),
    ('  - Mutual fund / SIP: on MutualFunds add ONE row per fund - enter Owner, then pick',),
    ('    the Scheme Name from the DROPDOWN (Fund House and ISIN fill in from MF_Master).',),
    ('    Log every SIP installment / lump sum on MF_SIP the same way (+ Date, Amount, NAV).',),
    ('    Invested, Avg cost NAV, Return % and XIRR all compute on the MutualFunds sheet.',),
    ('    Redemptions: enter them on MF_SIP with a negative Amount.',),
    ('  - Fixed deposit: add a row on FixedDeposits (principal, rate, dates, comp./yr).',),
    ('  - PPF: add a row on PPF (current balance + as-on date).',),
    ('  - Bond: add a row on Bonds (qty, face value, buy/current price, coupon, maturity).',),
    ('  Yellow/blue cells are for you to type; the grey computed columns fill themselves.',),
    ('  Rows are pre-formatted well beyond the current data, so just keep typing downward.',),
    (),
    ('UPDATE PRICES',),
    ('  - Close this file, then run "Update Portfolio" (double-click). One run refreshes',),
    ('    everything: share prices (BSE/NSE by ISIN), fund NAVs (AMFI), the master lists,',),
    ('    corporate actions, every XIRR figure and the FY-end estimate - after backing up',),
    ('    your file to the backups folder.',),
    ("  - Bonds: 'Current Price' updates automatically only when the ISIN traded on the",),
    ('    exchange; corporate bonds are illiquid, so type it manually when you have it.',),
    ("  - FD value and PPF need no price feed — FD compounds automatically to today's date.",),
    (),
    ('NOTES',),
    ('  - XIRR columns hold plain values written by the updater; run "Update Portfolio"',),
    ('    again after adding or changing any holdings.',),
    ('  - Equity was carried over from your demat files with the agreed cost basis.',),
    ("  - Don't rename the sheets — the Dashboard formulas reference them by name.",),
    ('PORTFOLIO XIRR, INFLATION & PROJECTION',),
    ("  - Dashboard 'Portfolio XIRR' blends the cashflows of Equity + Mutual Funds + FDs + PPF + Bonds.",),
    ('    "Update Portfolio" recomputes it, together with the per-class XIRR column on the Dashboard.',),
    ("  - PPF keeps no contribution history here, so it is estimated at its 'Rate %' from the as-on date.",),
    ("  - Bonds: fill the 'Buy Date' input column — rows without it are skipped. Coupons are not",),
    ('    tracked, so bond XIRR reflects price change only.',),
    ("  - 'Inflation % p.a.' on the Dashboard is yours to edit (default 7). 'Real return' and the whole",),
    ('    Projection sheet (20-year corpus trajectory chart) react instantly — no script run needed.',),
    ('  - The Projection assumes a constant return and no future contributions or withdrawals.',),
    ('MASTERS (MF_Master & Stock_Master sheets)',),
    ('  - MF_Master holds every AMFI scheme with an ISIN (Fund Name / Scheme Name / ISIN) and',),
    ('    feeds the Scheme dropdowns on MutualFunds and MF_SIP. Do not edit it by hand.',),
    ('  - Run "Update Portfolio" to refresh it (new/renamed schemes); the dropdowns',),
    ('    resize automatically. The refresh date shows in MF_Master!E2.',),
    ('  - A scheme missing from the master (delisted/merged fund)? Excel only warns - accept the',),
    ('    warning, then type Fund House and ISIN yourself on that row.',),
    ('  - Stock_Master feeds the Scrip dropdown on Equity the same way (pick the name, the',),
    ("    ISIN fills in). \"Update Portfolio\" refreshes it automatically from the day's bhavcopy:",),
    ('    new listings are ADDED, existing names never change (your picked rows keep working).',),
    ('    Delisted scrips: accept the warning and type the ISIN yourself.',),
    ('  - TYPE-AHEAD (2 steps): in a Scheme/Scrip/Bank cell, type the first letters and',),
    ('    press ENTER, then RE-OPEN the dropdown (click the arrow, or Alt+Down on the',),
    ('    selected cell) - the list now shows only names starting with what you typed.',),
    ('    To change an existing pick, clear the cell (Delete) first - the dropdown then',),
    ('    offers the full list again.',),
    ('  - Want to type WHILE the list is open? Update Excel: current Microsoft 365',),
    ('    (about version 2304 and newer) filters the dropdown live as you type, with',),
    ('    no workbook change needed. Older Excel cannot do this in any workbook.',),
    ('    No pop-ups here: if the ISIN stays blank after entering a name, it did not',),
    ('    match the master - re-open the dropdown and pick from it.',),
]

GUIDE_ROWS += _WHATS_NEW
